### ISSUE TITLE
2018.03.19 文档整理

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#1]
1. 整理一套文档模板；
2. 按模板整理相关文档；

**Comment by xcc333** [comment]
之前连的设备陆续交付文档，大家消化下原来的程序，如果设备采数有不稳定的，一起解决，全面提高稳定性，不用到处救火。

**Comment by HeathKang** [comment]
@majj 需要一期的设备清单，然后分一下文档任务
