### ISSUE TITLE
2018.03.19 chitu优化

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#2]
1. 测试当前chitu传输速度；
2. 得出瓶颈结论；
3. 优化新版chitu

**Comment by Pyligo** [comment]
OK!~~~~~

**Comment by majj** [comment]
chitu  -- MQTT --> EMQ ----> inflxudb1
                                  |
                                  +------> inflxudb2
EMQ到influxdb可用server端的chitu来中转。

**Comment by HeathKang** [comment]
## issues：
- AVL设备如果断网再上传的话，由于数据量较大，所以上传到最新的数据很慢

## solutions：
- 能否将chitu的传数规则修改，类似于栈的数据结构传数，后入先出，每次都传最新的数据，这样在断网恢复后，迅速上传最新的数据

**Comment by xcc333** [comment]
BIA出现的chitu问题是否已经解决？

**Comment by HeathKang** [comment]
@xcc333 chitu要准备用新版的chitu，需要拿到chitu新版后我评估一下需要多久能优化兼容完毕

**Comment by HeathKang** [comment]
已完成
