### ISSUE TITLE
正时、摩擦功、冷却液数据不稳定

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#24]
## issues：
- RE 程序用的ziyan版本，chitu却用的doctopus版本

## solutions
- 将chitu版本更换为ziyan版本适配

**Comment by HeathKang** [comment]
更换chitu版本后解决

**Comment by HeathKang** [comment]
## issues
- 日志挂载不太稳定
## solutions
- 安装日志挂载监控脚本

**Comment by YHYJ** [comment]
日志挂载监控脚本安装完成
