### ISSUE TITLE
工控机messages增长到过大，占满磁盘空间，导致程序崩溃

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#32]
## issues：
ziyan及chitu的console输出，导致messages增长过大，占满磁盘

## solutions：
1. 关闭ziyan及chitu的console输出
2. 设置系统logrotate，定期清理messages

**Comment by YummyLucky** [comment]
路径：../var/log/messages

**Comment by YummyLucky** [comment]
设计：按周清理，存储2周的message文件，删除早于2周的文件

**Comment by YummyLucky** [comment]
创建一个logrotate来轮循该文件，首先创建一个配置文件：
# vim /etc/logrotate.d/log-file
文件内容如下：——————————————
/var/log/messages {
    weekly
    rotate 5
    missingok
    notifempty
    create 644 root root
    postrotate
        /usr/bin/killall -HUP rsyslogd
    endscript
}
等待   review

**Comment by YummyLucky** [comment]
设备过多，用 fabric 编写部署脚本

**Comment by YummyLucky** [comment]
设备过多，用 fabric 编写部署脚本

**Comment by YummyLucky** [comment]
配置了一台 5E06，周一来看看状态（目前有最近的messages文件命名为messages-20180506）
配置过程中发现 /etc/logrotate.d/syslog 中有对messages文件进行存档操作，初步判断无影响——

**Comment by YummyLucky** [comment]
远程进入linux机器，alt+p，cd到/etc/logrotate.d/目录下，put -b messages-file

**Comment by YummyLucky** [comment]
夏工觉得7天数据过多，希望少存储一些

**Comment by YummyLucky** [comment]
所有工控机统一将rotate 7改成了rotate 2，改成2天的轮循。

**Comment by YummyLucky** [comment]
10.7.92.15 的磁盘占用比达到了76%，余下 3G 的空间。需每天查看磁盘占用增长情况。
