### ISSUE TITLE
风洞实验室空调子系统ziyan程序崩溃

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#39]

**Comment by Pyligo** [comment]
需要设备名ip信息，以及是否可以远程debug还是需要到现场看，任务紧急程度。因为现在有多个任务我需要协调下时间，给任务排序，确定大致解决方法。

**Comment by HeathKang** [comment]
目前未发现异常，先关闭掉，待再有异常时，重新监控起来
