### ISSUE TITLE
MTS柔性设备多个实验开启，一个关闭显示整个设备已停

### ISSUE THREAD

**Issue by Pyligo** [Mabo-IoT/mission-brief#45]
设备开启状态status的确定重新确立方案。
难点：从日志信息并不能看出开启的多个实验有什么不同，不能直接只从日志信息里解析出来。
突破口：不同实验写入不同的日志文件，但名字由工程师自己根据实验特点自己起，具有随机性。且不能确定出该实验真正结束时间。

**Comment by majj** [comment]
一台设备的不同部分，入MTS 24通道的前悬、后悬，不同部分同时运行，分别记录到不同的日志里。表结构中有tag区分eqpt-part的。

**Comment by Pyligo** [comment]
程序修改完成，待部署

**Comment by Pyligo** [comment]
连接redis出错， error 10060  timeout

**Comment by Pyligo** [comment]
将localhost修改为127.0.0.1，成功部署~！
