### ISSUE TITLE
AND设备程序开发、测试、部署

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#46]
## solutions：
- XML文件解析

**Comment by ziserendexin** [comment]
通过labcentral获取多台的信息，并分析xml处理数据后上传
- [x ] 身份验证
- [x ]取数，分析测试
- [ ] 对方完成所有设备的配置
- [ ] 数据对其、清洗
- [ ] 数据正确性确认

**Comment by HeathKang** [comment]
已完成
