### ISSUE TITLE
设备状态数据准备之一

### ISSUE THREAD

**Issue by majj** [Mabo-IoT/mission-brief#49]
Kapacitor提取influxdb中的最新设备状态，保存在新的influxdb表中，避免在现有表中用 last( ) 取最后状态。

**Comment by HeathKang** [comment]
## 关于last()的一点想法
-  直接用last()，而不加时间限制的话，会对数据进行遍历，从而增加内存使用；
- 如果用last()后，再加```time>xxxx```，会不会查询的更快呢？

**Comment by HeathKang** [comment]
需求不明
