### ISSUE TITLE
2018.03.19 广德  MTS设备  日志 +句柄   本机部署（3台）  

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#6]

**Comment by Pyligo** [comment]
计划3.22-3.23两天把模拟部署完广德MTS，保证运行无误。

1. 先在本机跑通------------------------------3.22
2. 然后虚拟机和本机模拟设备和黑盒子-----3.23

**Comment by Pyligo** [comment]
完成情况：
       在本机用watchman成功将MTS_RPC及MTS_station日志解析传输到influxdb
接下来任务：
       1. 了解在Windows上将python程序注册成服务
       2. 进一步熟悉watchman及插件写法

**Comment by Pyligo** [comment]
3月前完成：
熟悉了取句柄的程序，模拟运行了watchman上传日志。
清明节后要完成：
1.在现场查看一下取句柄的窗口
2.模拟在新设备上取句柄的流程
3.整个日志及取句柄的部署流程确定下来，准备好资源，拟写一个部署文档
