### ISSUE TITLE
时间同步

### ISSUE THREAD

**Issue by YHYJ** [Mabo-IoT/mission-brief#63]
生产服务器作为NTP服务器，完成设备的时间同步
（广德、烟台、武汉暂不考虑，大约19台）

**Comment by YHYJ** [comment]
可以远程访问的机子已经完成，剩下需要现场和2台需要安装ntpdate但安装报错乱码的需要解决

**Comment by YHYJ** [comment]
2台机器显示乱码，且灭有ntpdate无法进行同步，待解决；
5台机器无法连接115，报夏工。

**Comment by ziserendexin** [comment]
10.7.93.129 
装完以后，没啥问题。

但稍微学习了点Linux相关。。

**Comment by YHYJ** [comment]
乱码是CRT的问题，编码设置成UTF8就行；
2台没有ntpdate的已安装完成；
还剩下5台无法连接115的和需要现场部署的win的机器。

**Comment by HeathKang** [comment]
已完成
