### ISSUE TITLE
共享文件夹监控脚本BUG修复

### ISSUE THREAD

**Issue by YHYJ** [Mabo-IoT/mission-brief#78]
[共享文件夹挂载状态监控脚本](https://github.com/Mabo-IoT/monitor_shared-folders)在检测挂载状态方面存在BUG：已挂载但挂载状态检测为0，需修复。

**Comment by ziserendexin** [comment]
问题在于，使用
mount | grep {} | wc -l 查询挂载，检测挂载。
对于down的，此时mount中有这个。

所以可能需要二次检测，emm，王斌使用ll命令来检测，感觉效率太慢了。
这里，如果ls挂掉的设备，会很慢。


日志比对没有发现问题。
两个异常的情况：
a、ping上，挂不了，正常显示
b、没挂上，但ping的上的，也显示正常
需求复现

复现需求回显：
cat mount.log | tail -n 100
ll share 目录
mount | grep {} | wc -l 对应的挂载点
如果可以，在py中获取 os.system("mount | grep {} | wc -l"

修改点：
1、31行的FileHandler(log_file).push_application()，改为RotatinFileHandler的形式
2、mount_status函数中，subprocess.getoutput改为，os.system

修改的差不多了。
有一个问题，不知道为什么，os.system会返回两个值。。。。一个代表挂载上的2，一个是0.。。0是什么鬼啊

明天问问，继续吧。

具体没啥问题，就是测试用的Linux，返回值异常。。。emmm，有趣，but why？

**Comment by ziserendexin** [comment]
1、需要优化监控方式
2、需要查找是否有其他的挂载方式
3、需要继续定位，挂载上，但显示没挂载的问题

————存在这样的情况，挂载上，然后拔网线，插回去，此时会存在bug，需要使用另外的方式检查挂载情况。
————mount这条命令，只是读取/etc/mtab里面的信息，这个信息并不是实时监测的。

同时ll、ls虽然可以监测，但依然感觉不准确，并且很慢

**Comment by ziserendexin** [comment]
尝试使用samba(康宁提议)
使用samba进行挂载管理。
阅读文档、安装等

**Comment by ziserendexin** [comment]
http://cn.linux.vbird.org/linux_server/0330nfs.php
--


鸟哥的Linux关于挂载的一些说明。周四学习下，如果这个没啥问题，就不考虑装samba了，对于中间机，能少装点东西就少点吧。。。

**Comment by ziserendexin** [comment]
1、为什么要用shell脚本来挂载而不是直接os.system？是有什么特别的考量么？
2、用的是/usr/bin/sh而不是/bin/sh...虽然应该没有区别

**Comment by ziserendexin** [comment]
感觉使用samba会好一些？支持window和Linux

**Comment by majj** [comment]
不建议采用共享目录方式采集日志
[filebeat faq](https://www.elastic.co/guide/en/beats/filebeat/current/faq.html)

系统重装的问题是运维的问题，不要在错误的方向上找正确的答案。

**Comment by majj** [comment]
filebeat装设备工控机上，redis装中间机上。一旦重装系统，客户应按手册，通过一键部署自行装上filebeat，安装程序根据设备电脑IP去寻找正确的配置文件（曾正常使用的配置文件）。

**Comment by ziserendexin** [comment]
不建议在windows上装。
缺点：
1、filebeat的安装依赖于PowerShell，虽然这是个微软的东西，但不是每个都有。
2、filebeat安装前要安装Elastic Stack（文档上这么说）。
3、window只有win7以上支持docker，所以也没法使用docker统一维护升级。
4、window上的filebeat可能不与总的server直连，会导致没有任何方法进行远程修改，只能到现场进行维护配置升级。
——PS：后续可以使用Gitlab+docker实现统一管理所有的镜像及单独的配置文件，同时进行自动更新。
5、官方举例中的缺点是更改文件标识符导致重新加载。
6、工厂方对于在window上装太多东西，会有各种意见，如果只是一个共享并保证共享的运行，这个对于他们是可以接受的，但如果还要装其他的程序，如果他们的程序挂了(可能是因为其他的问题)，就会考虑是我们的程序导致的，又增加了我们的后续维护成本。

另一方面：
在Linux上，可以用docker啊！改个配置文件，然后docker一行代码就能启动啦！

**Comment by majj** [comment]
1、filebeat编译后就一个exe，拷贝上就可以用，哪里看到依赖PowerShell的？
2、filebeat不依赖Elastic，配置指向Redis就可以了；
3、filebeat作为agent，放宿主机上，跟docker有什么关系？
4、filebeat就是作为agent放宿主机的，为什么总要远程修改？需要修改是因为事先的设计缺失引起的。
5、更改文件标识符是什么场景的操作，有没有测过会不会发生这样的问题？
6、好比HPU要装传感器，传感器不装HPU上，还能装什么地方？
7、了解一下别人是如何采集日志程序的。
8、共享目录的方式，到底存在哪些问题？
总之，要把原理和各种问题想清楚，才有正确的决策。

**Comment by ziserendexin** [comment]
1、filebeat只依赖自身，只有一个exe，这个部署和运维难度的确就到了可以接受的阶段。
filebeat放宿主机，可以少一个挂载监控，相关接口也不用操心。
但对于远程更新，如果再装confd，这样宿主机装的东西略多啊。
2、安全的问题，这边宿主机、中间机都是在内网里面。不太需要考虑这个吧。
3、组网的问题，宿主机与115的服务器没有直连。相当于这边宿主机是与中间机组局域网直连，共享的可靠性，应该挺高的。

今天先看看filebeat的源码，了解下如何采集，看下不推荐的具体原因。

**Comment by ziserendexin** [comment]
测试结果：
如果挂载正常，一切ok。

组网示例：
win—share——【1】——log—Linux—log———【2】———filebeat—docker


但如果挂载断了，本地的【1】的log这里会显示不正常，进不去。此时docker中的filebeat显示依然在监控。
此时需要重新挂载【1】，umount【1】后，filebeat显示文件被移除，mount【1】后，依然显示被移除。

所以如果使用docker的话，网络挂载【1】断了，100%会导致【2】异常，并且无法恢复。

如果不适用docker，不挂【2】，也可能会在标识符等地方产生异常。

结论：
网络挂载存在巨大问题。同时mount挂掉以后，会导致docker存在无法恢复的bug。

舍弃此方案。

**Comment by ziserendexin** [comment]
同时从设计逻辑上来看，存在很多唯一标识符的很多潜在问题。

无论什么方案，都不应使用网络挂载。

具体研究过程，见附件。

[filebeat网络挂载问题.txt](https://github.com/Mabo-IoT/mission-brief/files/2200502/filebeat.txt)

**Comment by majj** [comment]
+1
