### ISSUE TITLE
2018.03.19 广德 油泵耐久试验台架 Firebird数据库 白盒子访问共享文件夹（1台）

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#8]
Firebird 关系型数据库

**Comment by YummyLucky** [comment]
寻找合适环境进行配置

**Comment by YummyLucky** [comment]
Firebird 环境配置完成，下一步研究它的常用方法，为开发脚本做前期准备

**Comment by YummyLucky** [comment]
熟悉doctopus框架，用框架实现Firebird取数

**Comment by HeathKang** [comment]
# [开发中](https://github.com/Mabo-IoT/GD_firebird)
- [scripts 取数脚本以及测试脚本已开发完毕](https://github.com/Mabo-IoT/GD_firebird/tree/master/scripts)
- 下一步写入Doctopus库中

**Comment by HeathKang** [comment]
已写入doctopus，开发基本完毕

**Comment by HeathKang** [comment]
录入文档

**Comment by HeathKang** [comment]
#31
