### ISSUE TITLE
高速拉伸机部署

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/mission-brief#82]
参考日志处理

**Comment by Pyligo** [comment]
为李工开发写出的watchman程序
6月29日周五拿到程序及log样例：

1. 只上传warning字段及status状态。

2.  时间戳处理同MTS

下周部署工控机，将日志共享出来，再将watchman程序部署上

**Comment by Pyligo** [comment]
工控机环境准备完毕，待去现场共享文件并部署工控机，拟定周五下午

**Comment by Pyligo** [comment]
7月9号，部署高速拉伸机：
设备号：PEC0-07628
IP:10.7.205.12
设备电脑：192.168.1.3
盒子：192.168.1.2
LAN1 EIM网络
LAN2 局域网

- [ ]  5米网线不够长，需要采购更长网线
- [ ]  需要采购固定网线所用的材料220cm

**Comment by Pyligo** [comment]
7月20号
网线已部署。
数据上传正常

- [ ] 自动挂载脚本的部署
