### ISSUE TITLE
中间机使用docker的研究

### ISSUE THREAD

**Issue by ziserendexin** [Mabo-IoT/mission-brief#87]
对中间机使用docker，进行环境的搭建。同时可以使用其他软件对docker进行自动更新。

**Comment by ziserendexin** [comment]
base研究

[docker特性及搭建规划v0.1.pptx](https://github.com/Mabo-IoT/mission-brief/files/2158104/docker.v0.1.pptx)

**Comment by ziserendexin** [comment]
尝试下载官方的centos/python3.6-centos7的，发现还需要安装S2I的镜像。。。Orz。。。还是用centos7开始进行构建

**Comment by ziserendexin** [comment]
使用compose完成docker中间机的简单调试：
redis+filebeat*2

明日再丰富下，争取把ziyan也给加上。

**Comment by ziserendexin** [comment]
docker server方面，registry已经装好了。但没法只能使用
docker pull ourserver.xx/influxdb 
而不是直接
docker pull influxdb
tag方面需要复杂一层。

**Comment by ziserendexin** [comment]
利用mts的程序,进行尝试，出现redis问题，虽然已经解决redis问题。
但倩工表示弃用docker。
现准备在and上使用。程序跑起来没问题，等待对方配置完成后，就可以

**Comment by HeathKang** [comment]
docker研究透彻
